version: "2"

networks:
  cuckoo-net:
    driver: bridge

services:
  build_image:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - CUCKOO_UID=1000
    image: amf_cuckoo:0.23
    networks:
      - cuckoo-net
  
  mongo:
    container_name: mongo
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - cuckoo-net

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cuckoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    networks:
      - cuckoo-net

  cuckoo:
    container_name: cuckoo
    depends_on:
      # - build_image
      - postgres
      - mongo
    image: amf_cuckoo:0.23  
    command: daemon
    ports:
      - "2042:2042"
      # - "18083:18083"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    volumes:
      - ./conf/:/cuckoo/conf/
      - ./volumes/cuckoo-tmp/:/tmp/cuckoo-tmp/
      - ./volumes/cuckoo-tmp-cuckoo/:/tmp/cuckoo-tmp-cuckoo/
      - ./volumes/storage/:/cuckoo/storage/
    env_file:
      - ./config-file.env
    restart: unless-stopped
    networks:
      - cuckoo-net
      
  web:
    container_name: cuckoo_web
    depends_on:
      - cuckoo
    image: amf_cuckoo:0.23  
    command: web
    ports:
      - "9091:31337"
    volumes:
      - ./volumes/cuckoo-tmp/:/tmp/cuckoo-tmp/
      - ./volumes/cuckoo-tmp-cuckoo/:/tmp/cuckoo-tmp-cuckoo/
      - ./volumes/storage/:/cuckoo/storage/
    env_file:
      - ./config-file.env
    restart: unless-stopped
    networks:
      - cuckoo-net

  api:
    container_name: cuckoo_api
    depends_on:
      - cuckoo
    image: amf_cuckoo:0.23
    command: api
    ports:
      - "9092:1337"
    volumes:
      - ./volumes/cuckoo-tmp/:/tmp/cuckoo-tmp/
      - ./volumes/cuckoo-tmp-cuckoo/:/tmp/cuckoo-tmp-cuckoo/
      - ./volumes/storage/:/cuckoo/storage/
    env_file:
      - ./config-file.env
    restart: unless-stopped
    networks:
      - cuckoo-net

volumes:
  cuckoo-data:
  mongo-data:
  postgres-data:
